#!/bin/bash
#
# Usage:
#  build
#
# This program builds the ds-irods-rs-onbuild image that forms the base image
# for CyVerse Data Store resource server images. Each build is tagged with the
# number ISO 8601 style build time.

readonly ExecName=$(readlink --canonicalize "$0")
readonly BaseDir=$(dirname "$ExecName")

readonly ImageName=cyverse/ds-irods-rs-onbuild


main()
{
  local tag
  tag=$(date --utc '+%Y-%m-%dT%H-%M-%S')

  docker pull "$ImageName":latest

  local lastId
  lastId=$(docker image inspect "$ImageName":latest | jq .[0].Id)

  "$BaseDir"/irods-netcdf-build/build centos7
  "$BaseDir"/irods-setavu-plugin/build centos7
  docker build --tag "$ImageName":"$tag" "$BaseDir"

  local currentId
  currentId=$(docker image inspect "$ImageName":"$tag" | jq .[0].Id)

  if [ "$currentId" != "$lastId" ]
  then
    docker tag "$ImageName":"$tag" "$ImageName":latest
    docker push "$ImageName":"$tag"
    docker push "$ImageName":latest
  else
    docker rmi "$ImageName":"$tag"
  fi
}


set -e
main
